name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: sudo apt-get update; sudo apt-get install -y libspeechd-dev libasound2-dev libudev-dev
      if: ${{ runner.os == 'Linux' }}

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

  rustfmt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt

    - name: Run rustfmt
      run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - run: sudo apt-get update; sudo apt-get install -y libspeechd-dev libasound2-dev libudev-dev
      if: ${{ runner.os == 'Linux' }}

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy

    - name: Run clippy
      run: cargo clippy -- -D warnings

  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4

      - run: sudo apt-get update; sudo apt-get install -y libspeechd-dev libasound2-dev libudev-dev
        if: ${{ runner.os == 'Linux' }}

      - name: Install Rust
        run: rustup update stable

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
